name: linux-build
on:
  push:
    branches: [ "7.4.x-4.8.x" ]
    tags:
      - 7.4.*-4.8.*-r*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          branch: edge
          packages: >
            vim alpine-sdk xz autoconf automake linux-headers clang-dev clang lld libtool cmake bison re2c zlib-dev
      - name: Cache Static Build
        id: cache-static-deps
        uses: actions/cache@v3
        with:
          path: |
            ./thirdparty
            ./pool
          key: ${{ runner.os }}-7.4.x-4.8.x-static-deps
      - name: init dep
        run: |
          ln -s ${{ github.workspace }}/  /work
          mkdir -p pool/lib pool/ext thirdparty
          apk add php php-pear php-openssl
          ./prepare.php linux ${{ github.workspace }}/..
          apk del php php-pear php-openssl
          chmod +x make.sh
        shell: alpine.sh --root {0}
      - name: build deps
        run: |
          ./make.sh all-library
        shell: alpine.sh --root {0}
      - name: make configure
        run: |
          ./make.sh pkg-check
          ./make.sh config
        shell: alpine.sh --root {0}
      - name : make build
        run: |
          ./make.sh build
        shell: alpine.sh --root {0}
      - name: test
        run: |
          ./bin/swoole-cli --version
          ./bin/swoole-cli -ini
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: swoole-cli-linux-${{ github.sha }}
          path: |
            bin
          retention-days: 5
      - if: startsWith(github.event.ref, 'refs/tags')
        name: compress binrary
        run: |
          cd bin
          strip swoole-cli
          tar -cJvf swoole-cli.tar.xz swoole-cli LICENSE
          mv swoole-cli.tar.xz ../swoole-cli-linux.x64-${{ github.ref_name }}.tar.xz
      - if: startsWith(github.event.ref, 'refs/tags')
        name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            swoole-cli-linux.x64-${{ github.ref_name }}.tar.xz


