name: mac-build
on:
  push:
    branches: [ "7.4.x-4.8.x" ]
    tags:
      - 7.4.*-4.8.*-r*-beta

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Static Build
        id: cache-static-deps
        uses: actions/cache@v3
        with:
          path: |
            ./opt
            ./pool
            ./thirdparty
          key: ${{ runner.os }}-7.4.x-4.8.x-static-deps
      - name: init deps
        run: |
          mkdir -p pool/lib pool/ext thirdparty opt
          ln -s ${{ github.workspace }}/opt ${{ github.workspace }}/../
          ./prepare.php macos ${{ github.workspace }}/..
          chmod +x make.sh
          brew uninstall --ignore-dependencies oniguruma
          brew uninstall --ignore-dependencies brotli
          brew uninstall --ignore-dependencies freetype
          brew uninstall --ignore-dependencies libomp
          ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
          brew install bison automake re2c
          rm -rf ../opt/usr/lib/*.dylib
      - if: ${{ steps.cache-static-deps.outputs.cache-hit != 'true' }}
        name: build deps
        run: |
          wget https://sourceforge.net/p/giflib/bugs/_discuss/thread/4e811ad29b/c323/attachment/Makefile.patch -O pool/lib/giflib.patch
          ./make.sh all-library
          rm -rf ../opt/usr/lib/*.dylib
      - name: make configure
        run: |
          ls -al ../opt/
          PATH="/usr/local/opt/bison/bin:$PATH" ./make.sh pkg-check
          PATH="/usr/local/opt/bison/bin:$PATH" ./make.sh config
          sed -i '' 's/-ne //g' ./main/php_config.h
      - name: make build
        run: |
          PATH="/usr/local/opt/bison/bin:$PATH" ./make.sh build
      - name: test
        run: |
          otool -L ./bin/swoole-cli
          ./bin/swoole-cli --version
          ./bin/swoole-cli -ini
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: swoole-cli-macos-${{ github.sha }}
          path: |
            bin
          retention-days: 5
#      - if: startsWith(github.event.ref, 'refs/tags')
      - name: compress binrary
        run: |
          cd bin
          tar -cJvf swoole-cli-${{ github.sha }}.tar.xz swoole-cli LICENSE
          mv swoole-cli-${{ github.sha }}.tar.xz ../swoole-cli-${{ github.sha }}.tar.xz
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew reinstall curl
      - name: Test background
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
      - if: startsWith(github.event.ref, 'refs/tags')
        name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: swoole-cli-${{ github.sha }}.tar.xz
          asset_name: swoole-cli-macos.x64-${{ github.ref_name }}.tar.xz
          tag: ${{ github.ref }}
          overwrite: true
