name: mac-build
on:
  push:
    branches: [ "7.4.x-4.8.x-grpc" ]

jobs:
    build:
        runs-on: macos-latest
        steps:
          - uses: actions/checkout@v2
          - name: Cache Static Build
            id: cache-static-deps
            uses: actions/cache@v3
            with:
              path: |
                ./opt
                ./pool
                ./thirdparty
              key: ${{ runner.os }}-static-deps
          - name: init deps
            run: |
              mkdir -p pool/lib pool/ext thirdparty opt
              ln -s ./opt ../opt
              ls -al ../
              ls -al
              ./prepare.php macos /Users/runner/work/swoole-cli
              brew uninstall --ignore-dependencies oniguruma
              brew uninstall --ignore-dependencies brotli
              brew uninstall --ignore-dependencies freetype
              ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
              brew install bison automake re2c
          - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
            name: build deps
            run: |
                wget https://sourceforge.net/p/giflib/bugs/_discuss/thread/4e811ad29b/c323/attachment/Makefile.patch -O pool/lib/giflib.patch
                ./make.sh all-library
#          - name: make configure
#            run: |
#              PATH="/usr/local/opt/bison/bin:$PATH" ./make.sh config
#          - name: make build
#            run: |
#              PATH="/usr/local/opt/bison/bin:$PATH" ./make.sh build
#              otool -L ./bin/swoole-cli
          - name: 'Upload Artifact'
            uses: actions/upload-artifact@v3
            with:
              name: swoole-cli-macos-${{ github.sha }}
              path: |
                bin
              retention-days: 5
