name: mac-build
on:
  push:
    branches: [ "7.4.x-4.8.x-grpc" ]

jobs:
    build:
        runs-on: macos-latest
        steps:
          - name: install dependencies
            run: brew install php
          - uses: actions/checkout@v2
          - name: init deps
            run: |
              mkdir -p pool/lib pool/ext
              mkdir -p ../opt
              sed -i  's/\/Users\/sean\/Documents\/php-work\/swoole-cli-4.x\/\/Users\/runner\/work\/swoole-cli\//' prepare.php
              ./prepare.php
              cat prepare.php
              cat ext/protobuf/config.m4
              cat ext/grpc/config.m4
