name: mac-build
on:
  push:
    branches: [ "7.4.x-4.8.x-grpc" ]

jobs:
    build:
        runs-on: macos-latest
        steps:
          - uses: actions/checkout@v2
          - name: init deps
            run: |
              mkdir -p pool/lib pool/ext
              mkdir -p ../opt
              ./prepare.php macos /Users/runner/work/swoole-cli
              cat prepare.php
              cat ext/protobuf/config.m4
              cat ext/grpc/config.m4
